### ISSUE TITLE
[trace] Tracker

### ISSUE THREAD

**Issue by at15** [dyweb/go.ice#11]
- [ ] wrap database driver in adapter?

TODO

- [ ] #28 add abstraction layer between open tracing interface and implementations

## Ref

- Dapper https://github.com/at15/go.ice/issues/11
- https://github.com/census-instrumentation/opencensus-go
- https://rakyll.org/latency-profiling/
  - talks about `os/exec` `database/sql` `net/http` which we can do in go.ice while go itself does not support it 
- https://rakyll.org/profiler-labels/ it is supported in opencensus-go, I think we could add this in our tracing library so it can works for opentracing
- [ ] https://github.com/lttng never heard of it before ... found when google ceph zipkin (it's a gsoc project I saw in 2016) http://victoraraujo.me/babeltrace-zipkin/
- **https://github.com/mitchellh/go-server-timing** support send timing to browser, just flat span though
- https://software.intel.com/en-us/articles/pin-a-dynamic-binary-instrumentation-tool Intel Pin tool ... this should be put into benchhub though ...

**Comment by at15** [comment]
not high priority
